# Generated by Django 5.2.10 on 2026-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, default='default_user', max_length=100)),
                ('query', models.CharField(max_length=500)),
                ('primary_characteristic', models.CharField(blank=True, default='', max_length=50)),
                ('domains', models.JSONField(default=list)),
                ('entities_mentioned', models.JSONField(default=list)),
                ('scenarios_used', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
