# Generated by Django 5.2.10 on 2026-02-02 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario', models.CharField(max_length=255)),
                ('variant', models.CharField(max_length=255)),
                ('size_mode', models.CharField(blank=True, default='', max_length=50)),
                ('feedback_type', models.CharField(choices=[('size', 'Size Adjustment'), ('issue', 'Issue Report')], default='issue', max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Full feedback payload')),
                ('device_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WidgetRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_id', models.CharField(db_index=True, max_length=255)),
                ('rating', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('rated_at', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, default='', help_text='Browser fingerprint or device identifier', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rated_at'],
                'constraints': [models.UniqueConstraint(fields=('entry_id', 'device_id'), name='unique_rating_per_device')],
            },
        ),
    ]
